### ISSUE TITLE
Invert Mouse Y Axis

### ISSUE THREAD

**Issue by Hawkmoon9** [iamclint/Zeal#1]
Thank you so much for this. Seriously.
And so i feel like a demanding DB for asking this but can you add Invert Y Axis? The in-game option isnt working now. I have always inverted Y axis in games. Since 1982 with Flight Simulator 1, i have inverted the Y axis. i know i must be a freak and weirdo but could you please add this option? I will love you forever (i already love you lots). I tried a strange app from a dark corner of gaming internet and it worked but wont let me move mouse pointer from one monitor to another and locks up game sometimes.  WIn10 cant seem to do it. Logitech software cant do it. 

You are our only savior. Me and the Invert Y axis freaks and geeks. You are Flash Gordon and the Highlander rolled into 1 mega hero. And so we pray and ask humbly on our /kneel knees. Is this possible? thank you sir/madam and have a good day.

**Comment by iamclint** [comment]
pushed the changes that check the in games invert mouse option and negates the mouse movement on the y axis.
