### ISSUE TITLE
/hidec looted's trampoline not functioning under OldUI

### ISSUE THREAD

**Issue by sammynilla** [iamclint/Zeal#22]
The trampoline `release_loot()` is failing to even trigger on OldUI for whatever reason. Tried to print some diagnostic info inside of it only to find out it wouldn't function at all.

I guess this means that the pointer for `Zeal::EqGame::EqGameInternal::fn_releaseloot` is in a different location?

**Comment by iamclint** [comment]
Yes its probably a new ui only function, I think this hook will get re-addressed soon

**Comment by iamclint** [comment]
Added a hook for this

**Comment by iamclint** [comment]
added a hook

**Comment by iamclint** [comment]
Added a hook to fix this problem
