### ISSUE TITLE
Auto-stand checks not processing properly on NewUI?

### ISSUE THREAD

**Issue by sammynilla** [iamclint/Zeal#23]
```cpp
if (Zeal::EqGame::LootWnd && Zeal::EqGame::LootWnd->IsOpen && Zeal::EqGame::LootWnd->IsVisible)
{
    Zeal::EqGame::EqGameInternal::CLootWndDeactivate((int)Zeal::EqGame::LootWnd, 0);
    return;
}
else if (Zeal::EqGame::SpellBookWnd && Zeal::EqGame::SpellBookWnd->IsVisible)
    return;
```

The loot window check doesn't seem to close the active loot window (which would cause the user to stand) and the spell book window check doesn't seem to prevent the user from standing up.

**Comment by iamclint** [comment]
The issue was the lootwnd pointer being initialized and read the pointer on init, created functions to read the pointer pointers to solve
