### ISSUE TITLE
/autoinv not working in macro with /pause

### ISSUE THREAD

**Issue by cpyle0819** [iamclint/Zeal#38]
Should `/autoinventory`, `/autoinv`, `/ai` work in isolation, but not when included with /pause.

**Comment by neyacinu** [comment]
What version of zeal are you using?  Use /zeal version in game.

**Comment by cpyle0819** [comment]
Not a valid command, so an outdated one I guess? 😅

**Comment by cpyle0819** [comment]
Are there instructions on building from source somewhere, or a place to get the lasted .asi?
I'm a lowly js dev :P

**Comment by cpyle0819** [comment]
Discovered it works fine without /pause.

**Comment by iamclint** [comment]
can you show me your hotkey setup that doesn't work

**Comment by iamclint** [comment]
this has been solved
