### ISSUE TITLE
/zealcam bug

### ISSUE THREAD

**Issue by zsinks** [iamclint/Zeal#48]
/zealcam doesnt apply when straffing.

**Comment by iamclint** [comment]
What do you mean it doesn't apply while strafing? you mean typing the command while also strafing?

**Comment by zsinks** [comment]
> What do you mean it doesn't apply while strafing? you mean typing the command while also strafing?

The command allows you to determine the sensitivity when looking around, but when you strafe, the sensitivity is still really high and hard to control.

**Comment by iamclint** [comment]
It's a strange bug that appears to only be you as far as I can tell, check your binds
