### ISSUE TITLE
mouselook is super sensitive with 0.1.50

### ISSUE THREAD

**Issue by KollinsPlays** [iamclint/Zeal#51]
I had the previous zeal and mouselook worked reasonably well in both 1st and 3rd person view, but after updating to the 0.1.50 zeal, mouselooking left or right is super fast and jerky. I tried adjusting the EQ options > mouse > mouse sensitivity and even when this setting is at 0, mouselook is still a little fast and jerky.

**Comment by KollinsPlays** [comment]
With further testing, I have noticed that the UP and DOWN mouselook movement seems normal or at least slower, but the LEFT and RIGHT mouselook seems faster and unaffected by the sensitivity value.

**Comment by iamclint** [comment]
can you use /zeal version
sounds like its not loaded
