### ISSUE TITLE
Zeal increases FPS so much the clients physics bugs out

### ISSUE THREAD

**Issue by kardo22** [iamclint/Zeal#56]
I noticed a massive increase in smoothness / fps installing the zeal mod, this is in over all a positive as the camera movement feels better, but the down side is that you fall so slow and other things like character animations are also bugging out because of the increased fps the full animations are not working properly, like running with a gnome the legs move slower than original.

Is there a way to install ZEAL but not increase the fps? If no, then is there a way to install zeal and not install the part where it adds third person view (which is the mod i believe is responsible for the fps increase, i could be wrong ofcourse). I would still like to be able to bind strafe right/left.

**Comment by iamclint** [comment]
Zeal does not do anything with your maximum fps
