### ISSUE TITLE
Cannot auto inventory (null) not enough bag space.

### ISSUE THREAD

**Issue by vvildcard** [iamclint/Zeal#63]
When I use /autoinventory without anything on the mouse tip, I get this message: "Cannot auto inventory (null) not enough bag space." It's not a huge deal, but it does spam because I have it tied to a forage macro that fires every time I push left/right. 

Zeal 3.0
Didn't happen in previous versions. 

As always, I love your work and thank you!!!

**Comment by iamclint** [comment]
this is just a debug message that needed to have a check in place if you even had an item on cursor, this is already resolved in code.
