### ISSUE TITLE
Suggestion: Slow turn speed setting

### ISSUE THREAD

**Issue by OsiViper** [iamclint/Zeal#68]
It would be nice to have the ability to adjust slow turn speed like FoV Setting. Like /slowturn to increase or decrease the speed at which you turn. Not sure if it's possible but it would be a nice QoL thing.

**Comment by neyacinu** [comment]
This has already been suggested and denied due to the fact this would lead
to automation of bards.

**Comment by iamclint** [comment]
Exactly as the previous commenter stated it would really lead to artificial circling for bards, I'm sure this is why it's being requested.
