### ISSUE TITLE
Mouse Sensitivity to Slow

### ISSUE THREAD

**Issue by jtcoyle** [iamclint/Zeal#69]
I have a 34" wide monitor and the rate that I am able to use mouse look is to slow.  I have increased mouse sensitivity to 100% but this still does not allow me to use mouse look correctly.  To get full range of motion, I have to place my mouse cursor to the very far edge the screen either on the right, left, top or bottom depending on witch way I want to mouse look.  I do no thave this problem when zeal files are not present.

**Comment by iamclint** [comment]
Have you attempted to change the zeal camera sensitivity?

**Comment by jtcoyle** [comment]
OK, I was able to go in the eqclient.ini file and increase all 4 for these from 0.100000 to:
MouseSensitivityX=0.500000
MouseSensitivityY=0.500000
MouseSensitivityX3rd=0.500000
MouseSensitivityY3rd=0.500000

This seems to have resolved the issue

**Comment by iamclint** [comment]
There is a UI piece included in the zip to modify these and also commanda

**Comment by iamclint** [comment]
There are commands and an included UI piece in the zip to modify this.
