### ISSUE TITLE
Cycle nearest NPC doesn't target a living NPC that shows 0% health

### ISSUE THREAD

**Issue by tybit323** [iamclint/Zeal#91]
Noticed when charming, I would break pet at 0%, or nuke him to 0% and root would break and I'd try to tab target and it wouldn't consider that NPC in the cycling.

I think this logic needs looked at, particularly `ent->HpCurrent > 0` maybe needing to be `>=` but not sure what else to consider... checking type for corpse also?

```
	if (!ent->IsHidden && ent->Type == type && ent->HpCurrent > 0 && ent->Level>0 && ent->TargetType<66)
	{
		if (ent->PetOwnerSpawnId)
		{
			Zeal::EqStructures::Entity* owner = Zeal::EqGame::get_entity_by_id(ent->PetOwnerSpawnId);
			if ((owner && (owner->Type == Zeal::EqEnums::EntityTypes::NPC || owner->Type == Zeal::EqEnums::EntityTypes::NPCCorpse)) || !owner)
				near_ents.push_back(ent);
		}
		else
			near_ents.push_back(ent);
```

**Comment by iamclint** [comment]
For now I just removed the health check, the original reasoning for putting that check in place may no longer exist with the targettype check.
